apply plugin: "kotlin-android"

dependencies {
	implementation "androidx.core:core-ktx:1.15.0"

	// https://developer.android.com/google/play/billing/release-notes
	def inapp_version = "9.1.0"
	implementation "com.android.billingclient:billing:${inapp_version}"
}

// Prevent the "More than one file was found with OS independent path 'META-INF/module_release.kotlin_module'" error
android {
	packagingOptions {
		exclude 'META-INF/*.kotlin_module'
	}
}
